---
  - hosts: webservers
    become: true
    vars: 
      path_to_app: "/var/www/html"

    vars_files:
      - ../vars/secret-variables.yml

    vars_prompt: 
      - name: "upload_var"
        prompt: "Upload the index php file ?"
      - name: "create_var"
        prompt: "Create info.php page ?"

    tasks: 
     - name: Use secret password here 
       debug:
         msg: "{{ secret_password }}"

     - name: Upload custom index page   
       copy: 
         src: ../index.php
         dest: "{{ path_to_app }}"
         mode: 0755 
       when: upload_var == 'yes'
       tags: upload

     - name: Create simple info page 
       copy:
         dest: "{{ path_to_app }}/info.php"
         content:  "<h1> Info about our webserver {{ ansible_hostname }} </h1>"
       when: create_var == 'yes'
       tags: create 

     - name: See dir contents
       command: ls -la {{ path_to_app }}
       register: dir_contents

     - name: Debug dir content 
       debug:
         msg: "{{ dir_contents }}"
       
     - name: Configure php.ini file 
       lineinfile:
         path: /etc/php.ini 
         regexp: ^short_open_tag
         line: 'short_open_tag=On' 
       notify: restart apache

    handlers:
     - name: restart apache
       service: name=httpd state=restarted